package juegos;

import java.time.LocalDateTime;

public class SesionJuego {
    private String id;
    private String idUsuario;
    private String idMesa;
    private LocalDateTime horaInicio;
    private LocalDateTime horaFin;
    private double totalHours;
    private double costoTotal;

    public SesionJuego(String id, String idUsuario, String idMesa, LocalDateTime horaInicio) {
        this.id = id; //TODO: Make it autogenerated
        this.idUsuario = idUsuario;
        this.idMesa = idMesa; //TODO: Replace by Juego instance
        this.horaInicio = horaInicio; //TODO: Replace by current LocalDateTime
    }

    public String getId() {
        return id;
    }

    public String getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getIdMesa() {
        return idMesa;
    }

    public void setIdMesa(String idMesa) {
        this.idMesa = idMesa;
    }

    public LocalDateTime getHoraInicio() {
        return horaInicio;
    }

    public void setHoraInicio(LocalDateTime horaInicio) {
        this.horaInicio = horaInicio;
    }

    public void iniciarCronometro() {
        System.out.println("Cronómetro iniciado.");
        //TODO: Implement cronometro and autorun with horaInicio
    }

    public void detenerCronometro() {
        System.out.println("Cronómetro detenido.");
        //TODO: Calculate totalHours and horaFin

    }

    public void reiniciarCronometro() {
        System.out.println("Cronómetro reiniciado.");
        //TODO: Reset totalHours and horaFin
    }

    public double calcularTotal(){
        //TODO: Calculate totalHours * Juego.precioHora
        return costoTotal;
    }

    public void finalizarSesion(LocalDateTime horaFin, double costoTotal) {
        //TODO: Make it an auto routine (detenerCronometro -> calcularTotal -> finalizarSesion)
        this.horaFin = horaFin;
        this.costoTotal = costoTotal;
        System.out.println("Sesión finalizada. Costo: " + costoTotal);
    }

}
